name: Publish
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check project
        uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: production=true pnpm build
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      # - name: Configure npm
      #   run: |
      #     echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: production=true pnpm build
      - name: Create PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
